name: Deploy to AWS Amplify

on:
  push:
    branches:
      - main  # Se activa automáticamente en push a main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests (opcional)
        run: npm test --if-present
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Deploy to AWS Amplify
        run: |
          # Triggear un nuevo build en Amplify
          aws amplify start-job \
            --app-id ${{ secrets.AMPLIFY_APP_ID }} \
            --branch-name main \
            --job-type RELEASE \
            --region ${{ secrets.AWS_REGION }}
        
      - name: Wait for deployment
        run: |
          echo "✅ Deployment iniciado en AWS Amplify"
          echo "Revisa el progreso en: https://console.aws.amazon.com/amplify/home?region=${{ secrets.AWS_REGION }}#/${{ secrets.AMPLIFY_APP_ID }}"
